- hosts: all
  become: yes
  tasks:
  - name: Install apache
    include: apache.yml
  - name: Install PhP
    include: php.yml
  - name: install wordpress
    include: wordpress.yml 

  - name: install database
    include: db.yml    